general:
  log_level: DEBUG
# define each camera properties and their role
cameras:
  - URI: /dev/video2
    roles: 
      - registration
      - recognition  
  - URI: /dev/video0
    roles:
      - recognition
# settings related to machine vision
vision_setting:
  face_DB_path: data/face_embeddings.sqlite3
  models_path: models/
  # these params has effect of performance
  skip_n_frames: 5
  interval_sec: 0.01 
  #####
  # crop setting 
  crop:
    tl_reduce_pct: [20, 20]
    br_reduce_pct: [20, 10]
  # settings related to detection
  detection:
    conf_thresh: 0.75
    nms_thresh: 0.6
    top_k: 10
    # settings about how much of frame to crop and use in vision models

    model_name: yunet
  # settings related to recognition
  recognition:
    conf_thresh: 0.75
    similarity_func: cosine
    model_name: sface
# health-check settings 
health_check:
  enabled: true
  push_to_server: false
  route: ""
  interval_sec: 5
# settings related to api
rest_api:
  port: 10821
  host: 0.0.0.0
  global_prefix: /api/v1
  global_timeout: 20


